# Generated by Django 5.2.14 on 2026-05-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_financialstatementperiod'),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecIngestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('cik', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('periods_saved', models.PositiveSmallIntegerField(default=0)),
                ('missing_fields_summary', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_ingest_jobs', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='SecIngestSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='telegram_bot.secingestjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='secingestjob',
            index=models.Index(fields=['status', 'created_at'], name='telegram_bo_status_528e81_idx'),
        ),
        migrations.AddIndex(
            model_name='secingestjob',
            index=models.Index(fields=['ticker', 'status'], name='telegram_bo_ticker_8ef5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='secingestjob',
            index=models.Index(fields=['cik'], name='telegram_bo_cik_bc88e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='secingestjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('ticker',), name='unique_active_sec_ingest_job'),
        ),
        migrations.AddIndex(
            model_name='secingestsubscriber',
            index=models.Index(fields=['chat_id', 'created_at'], name='telegram_bo_chat_id_39c751_idx'),
        ),
        migrations.AddIndex(
            model_name='secingestsubscriber',
            index=models.Index(fields=['notified_at'], name='telegram_bo_notifie_c9e748_idx'),
        ),
        migrations.AddConstraint(
            model_name='secingestsubscriber',
            constraint=models.UniqueConstraint(fields=('job', 'chat_id'), name='unique_sec_ingest_subscriber_job_chat'),
        ),
    ]
