# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_financialstatementperiod"),
        ("telegram_bot", "0002_secingestjob_secingestsubscriber_and_more"),
        ("users", "0002_watchlistitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000)),
                ("summary", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_articles",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyWatchlistReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_date", models.DateField()),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(choices=[("sent", "Sent"), ("skipped", "Skipped"), ("failed", "Failed")], max_length=16),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_watchlist_reports",
                        to="users.telegramuser",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(fields=["company", "published_at"], name="telegram_bo_company_8c4a93_idx"),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(fields=["source", "fetched_at"], name="telegram_bo_source_b34f81_idx"),
        ),
        migrations.AddConstraint(
            model_name="newsarticle",
            constraint=models.UniqueConstraint(fields=("url",), name="unique_news_article_url"),
        ),
        migrations.AddIndex(
            model_name="dailywatchlistreport",
            index=models.Index(fields=["report_date", "status"], name="telegram_bo_report__58542b_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailywatchlistreport",
            constraint=models.UniqueConstraint(fields=("user", "report_date"), name="unique_daily_watchlist_report_user_date"),
        ),
    ]
