# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_financialstatementperiod"),
        ("telegram_bot", "0003_newsarticle_dailywatchlistreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCompanyNewsAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_date", models.DateField()),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("fallback", "Fallback"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_news_analyses",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dailycompanynewsanalysis",
            index=models.Index(fields=["report_date", "status"], name="telegram_bo_report__436077_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailycompanynewsanalysis",
            constraint=models.UniqueConstraint(fields=("company", "report_date"), name="unique_daily_company_news_analysis"),
        ),
    ]
