# Generated by Django 5.2.14 on 2026-05-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='users.telegramuser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_watch_user_id_0813ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_watchlist_item_user_company')],
            },
        ),
    ]
