# Generated by Django 5.2.14 on 2026-05-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=32)),
                ('sector', models.CharField(blank=True, max_length=128)),
                ('industry', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('cik', models.CharField(blank=True, max_length=16)),
                ('instrument_type', models.CharField(choices=[('common_stock', 'Common stock'), ('reit', 'REIT'), ('etf', 'ETF'), ('fund', 'Fund'), ('spac', 'SPAC'), ('financial', 'Financial'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker'], name='companies_c_ticker_114800_idx'), models.Index(fields=['instrument_type'], name='companies_c_instrum_cc97cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'exchange'), name='unique_company_ticker_exchange')],
            },
        ),
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('source_url', models.URLField(blank=True)),
                ('as_of_date', models.DateField()),
                ('period_end_date', models.DateField(blank=True, null=True)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('ttm', 'Trailing twelve months'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pbr', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('psr', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('roic', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('operating_income', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('operating_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('free_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='LensScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_name', models.CharField(max_length=64)),
                ('scoring_version', models.CharField(max_length=32)),
                ('score', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(max_length=4)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16)),
                ('data_completeness', models.PositiveSmallIntegerField()),
                ('passed_rules', models.JSONField(blank=True, default=list)),
                ('failed_rules', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('required_extra_checks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_scores', to='companies.company')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_scores', to='companies.financialsnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='financialsnapshot',
            index=models.Index(fields=['source', 'as_of_date'], name='companies_f_source_3fb38d_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsnapshot',
            index=models.Index(fields=['period_type', 'period_end_date'], name='companies_f_period__2de97c_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialsnapshot',
            constraint=models.UniqueConstraint(fields=('company', 'source', 'as_of_date', 'period_end_date', 'period_type'), name='unique_financial_snapshot_source_period'),
        ),
        migrations.AddIndex(
            model_name='lensscore',
            index=models.Index(fields=['lens_name', 'scoring_version'], name='companies_l_lens_na_a8c247_idx'),
        ),
        migrations.AddIndex(
            model_name='lensscore',
            index=models.Index(fields=['confidence'], name='companies_l_confide_f43b95_idx'),
        ),
        migrations.AddConstraint(
            model_name='lensscore',
            constraint=models.UniqueConstraint(fields=('company', 'snapshot', 'lens_name', 'scoring_version'), name='unique_lens_score_version_per_snapshot'),
        ),
    ]
