# Generated by Django 5.2.14 on 2026-05-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='sec_companyfacts', max_length=64)),
                ('form_type', models.CharField(choices=[('10-K', '10-K'), ('10-K/A', '10-K/A'), ('10-Q', '10-Q'), ('10-Q/A', '10-Q/A')], max_length=8)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], max_length=16)),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('fiscal_period', models.CharField(max_length=8)),
                ('period_end_date', models.DateField()),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('accession_number', models.CharField(max_length=32)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('operating_income', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('eps_diluted', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('shareholders_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('current_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('operating_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('capital_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('dividends_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('collected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statement_periods', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'period_type', 'period_end_date'], name='companies_f_company_9a5526_idx'), models.Index(fields=['source', 'collected_at'], name='companies_f_source_69551e_idx'), models.Index(fields=['accession_number'], name='companies_f_accessi_82ebe3_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'source', 'accession_number', 'period_end_date', 'period_type'), name='unique_statement_period_source_accession')],
            },
        ),
    ]
