# Generated by Codex on 2026-06-03

from django.db import migrations, models

from stock_evaluator.companies.aliases import SEED_COMPANY_ALIASES, normalize_alias


def seed_aliases(apps, schema_editor):
    del schema_editor
    company_alias = apps.get_model("companies", "CompanyAlias")
    for values in SEED_COMPANY_ALIASES:
        company_alias.objects.update_or_create(
            normalized_alias=normalize_alias(values["alias"]),
            defaults={
                "alias": values["alias"],
                "ticker": values["ticker"],
                "company_name": values.get("company_name", ""),
                "alternative_tickers": values.get("alternative_tickers", []),
                "source": "seed",
            },
        )


def unseed_aliases(apps, schema_editor):
    del schema_editor
    company_alias = apps.get_model("companies", "CompanyAlias")
    company_alias.objects.filter(
        normalized_alias__in=[normalize_alias(values["alias"]) for values in SEED_COMPANY_ALIASES],
        source="seed",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_financialstatementperiod"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alias", models.CharField(max_length=128)),
                ("normalized_alias", models.CharField(max_length=128, unique=True)),
                ("ticker", models.CharField(max_length=16)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("alternative_tickers", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(choices=[("seed", "Seed"), ("manual", "Manual"), ("generated", "Generated")], default="seed", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="companyalias",
            index=models.Index(fields=["ticker"], name="companies_c_ticker_f4d9d4_idx"),
        ),
        migrations.AddIndex(
            model_name="companyalias",
            index=models.Index(fields=["source"], name="companies_c_source_d970e1_idx"),
        ),
        migrations.RunPython(seed_aliases, unseed_aliases),
    ]
